version: '3.9'

services:
  sm_assignment:
    image: php_assignment:latest
    container_name: php_assignment
    restart: "no"
    build:
      context: ./
      dockerfile: Dockerfile
      target: local
    volumes:
        - "./module:/app/module"
        - "./tests:/app/tests"

    ports:
      - "7777:80"

networks:
  default:
    name: sm_assignment
